.TH GBACKGROUND "1" "0.1" "Alejandro Garrido Mota"
.SH NAME
gbackground \- interval-based gnome background changer
.SH "SYNTAX"
.LP
.B gbackground
.SH DESCRIPTION
This program allow to change periodically the gnome background
in intervals of a second, it uses the gnome tools to do this.
The user indicates the source directory of the images.
.LP
This program was made using Gtk2 and Perl.
.LP
Homepage: http://www.mogaal.com/gbackground
.SH AUTHOR
gbackground is developed by <Alejandro Garrido Mota>.
.PP
This manual page was written by Alejandro Garrido Mota <garridomota@gmail.com>,
for the Debian project (but may be used by others).
